name: m10_sdk
description: SDK for interacting with M10 platform.
version: 0.21.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  convert: ^3.0.0
  cryptography: ^2.0.1
  grpc: ^3.0.2
  dio: ^4.0.0
  protobuf: ^2.0.0
  uuid: ^3.0.3
  recase: ^4.0.0
  equatable: ^2.0.3
  fixnum: ^1.0.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.20.1
  random_string: ^2.3.1
