name: m10_sdk
description: This package allows Flutter and Dart applications to interact with the M10 platform.
repository: https://github.com/m10io/sdk
version: 0.29.10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  convert: ^3.0.0
  cryptography: ^2.0.1
  dio: ^4.0.0
  equatable: ^2.0.3
  fixnum: ^1.0.0
  grpc: ^3.0.2
  path: ^1.8.0
  protobuf: ^2.0.0
  recase: ^4.0.0
  uuid: ^3.0.3

dev_dependencies:
  lints: ^2.0.1
  random_string: ^2.3.1
  test: ^1.20.1
