name: m10_sdk
description: This package allows Flutter and Dart applications to interact with the M10 platform.
repository: https://github.com/m10io/sdk
version: 0.35.9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  convert: ^3.0.0
  cryptography: ^2.0.1
  dio: ^5.2.1
  equatable: ^2.0.3
  fixnum: ^1.0.0
  grpc: ^4.0.4
  path: ^1.8.0
  protobuf: ^4.0.0
  recase: ^4.0.0
  uuid: ^3.0.3
  xid: ^1.0.12
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  random_string: ^2.3.1
  test: ^1.20.1
