listen_addr = "0.0.0.0:8080"
database_url = "postgres://m10bankemulator@localhost/m10bankemulator"
log_filter = "m10_bank_emulator=debug,m10_notifier=debug,sqlx=warn,info"
ledger_addr = "http://0.0.0.0:50051"
directory_addr = "https://develop.m10.net"
prometheus_port = "27777"

key_pair = "MFMCAQEwBQYDK2VwBCIEIFX1/JTSaE+IV9aM3SWMLhh6Gi8G3+Uu8rfQG4+jmqmfoSMDIQAYsbQ3kBzKG2ijScMH9jnRYg7JUCL+QQkum+Sc1NIPEg=="
bank_name = "M10 Bank"
short_name = "MTB"
swift_code = "MTBUSM10SB"

[oauth]
issuer   = "https://keycloak-app.m10.net/"
audience = "https://api.m10.net"

[bank]
type = "Emulator"
currencies = [{currency = "USD", account_name = "holding-usd", pre_fund_range = {start = 50000, end = 300000}}]
checking_account_start = 500000000

[currencies.usd]
code = "usd"
rtgs_addr = "http://0.0.0.0:50052"
cb_name = "M10 Reserve"
reserve_config = {nominal_balance = 1000000000, balance_threshold = 20}
cbdc_config = {customer_limit = 100000, nominal_margin = 10000000, margin_threshold = 20}
drc_config = {nominal_fraction = 20, fraction_threshold = 10}
asset = false

[currencies.ttt]
code = "ttt"
rtgs_addr = "http://0.0.0.0:50052"
cb_name = "M10 Reserve"
reserve_config = {nominal_balance = 1000000000, balance_threshold = 20}
asset = false
test = {account_owner = "6qot3U5hJXqxqzX6/k1ZgukkN3cbmtq3RG3oHRgym88=", ledger_account_name = "Bank A TTT"}

[notification]
type = "Mock"

[directory]
address = "https://develop.m10.net"
is_secure = true
