syntax = "proto3";

import "sdk/document.proto";

package m10.sdk;

// RoleBinding represents the binding of a Role to a set of subjects.
message RoleBinding {
  // Unique identifier (uuid) for the RoleBinding.
  bytes id = 1;
  // Human-readable name for the RoleBinding.
  string name = 2;
  // Reference to the Role being bound. This is expected to be the Role's ID.
  bytes role = 3;
  // List of subjects (public keys) this role binding applies to.
  repeated bytes subjects = 4;
  // List of expressions that further refine the scope of the role binding.
  repeated Expression expressions = 5;
  // If true, this RoleBinding applies universally, regardless of expressions or subjects.
  bool is_universal = 6;
  // ID (public key) of the owner of this RoleBinding.
  bytes owner = 7;
  // Timestamp (in milliseconds since Unix epoch) when this RoleBinding was created.
  uint64 created_at = 8;
  // Timestamp (in milliseconds since Unix epoch) when this RoleBinding was last updated.
  uint64 updated_at = 9;
  // Public key of the user who created this RoleBinding.
  bytes created_by = 10;
  // Optional description of this RoleBinding (max 100 characters).
  string description = 11;
  // Optional expiry time (unix ms). If set and the current time is past expiry time,
  // the binding is treated as if it does not exist. If absent = never expires.
  optional uint64 expires_at = 12;
  // Optional labels (metadata) of this RoleBinding (Key and Value must be 100 characters or less each).
  map<string, string> labels = 13;
  // List of attributes that might be used in expressions.
  repeated Attribute attributes = 14;
}

// Expression represents a conditional expression that refines the scope of a RoleBinding.
message Expression {
  // The collection the expression applies to.
  string collection = 1;
  // The actual expression string. The syntax and semantics of this string are context-dependent.
  string expression = 2;
}

// Attribute represents custom variable that might be used in MQL expressions to evaluate them
message Attribute {
  // Name of the attribute (may be any valid string value)
  string name = 1;
  // Actual value of the attribute (may be of any type supported by AttributeValue)
  AttributeValue value  = 2;

  // AttributeValue represents all possible types and their values to be used in attributes
  message AttributeValue {
    // Actual value, holds underlying type and its corresponding value
    oneof value {
      // Value of unsigned integer type
      uint64 uint_value   = 1;
      // Value of integer type
      int64 int_value     = 2;
      // Value of float type ('double' in protobuf is analog of Rust 'f64' type)
      double float_value  = 3;
      // Value of bool type
      bool bool_value     = 4;
      // Value of string type
      string string_value = 5;
    }
  }
}

// Role defines a set of permissions.
message Role {
  // Unique identifier for the Role.
  bytes id = 1;
  // ID (public key) of the owner of this Role.
  bytes owner = 2;
  // Human-readable name for the Role.
  string name = 3;
  // List of rules that define the permissions granted by this role.
  repeated Rule rules = 4;
  // Timestamp (in milliseconds since Unix epoch) when this Role was created.
  uint64 created_at = 5;
  // Timestamp (in milliseconds since Unix epoch) when this Role was last updated.
  uint64 updated_at = 6;
  // Public key of the user who created this Role.
  bytes created_by = 7;
  // Optional description of this Role (max 100 characters).
  string description = 8;
  // If true, role cannot be modified or deleted by any principal.
  bool immutable = 9;
  // Optional labels (metadata) of this Role (Key and Value must be 100 characters or less each)
  map<string, string> labels = 10;
}

// Rule specifies permissions on a particular collection.
message Rule {
  // The collection this rule applies to.
  string collection = 2;
  // Optional list of instance keys. If provided, the rule only applies to these specific instances within the collection.
  repeated Value instance_keys = 3;  // Assumes a Value message is defined elsewhere.
  // List of verbs allowed for this rule.
  repeated Verb verbs = 4;
  // Optional MQL expression of the rule. If provided, evaluates in runtime whenever actions, that require the rule, are triggered.
  optional string when = 5;
  // Types of variables declared in expression. All variables, that were declared in expression, must be annotated with their types here.
  map<string, Ty> types = 6;

  // Verb defines the actions a subject can perform on a resource.
  enum Verb {
    READ = 0;     // Read access
    CREATE = 1;   // Create access
    UPDATE = 2;   // Update access
    DELETE = 3;   // Delete access
    TRANSACT = 4; // Transaction access
    INITIATE = 5; // Initiate transaction
    COMMIT = 6;   // Commit transaction
    GRANT = 7;    // Allow granting this permission to others
    DENY = 8;     // Deny action
    REVOKE = 9;   // Allow revoking this permission from others
  }

  // Ty defines the type of variables that were declared in Rule expression.
  enum Ty {
    U8 = 0;       // Unsigned integer (8 bits)
    U16 = 1;      // Unsigned integer (16 bits)
    U32 = 2;      // Unsigned integer (32 bits)
    U64 = 3;      // Unsigned integer (64 bits)
    I8 = 4;       // Integer (8 bits)
    I16 = 5;      // Integer (16 bits)
    I32 = 6;      // Integer (32 bits)
    I64 = 7;      // Integer (64 bits)
    F32 = 8;      // Float (32 bits)
    F64 = 9;      // Float (64 bits)
    BOOL = 10;    // Boolean
    STRING = 11;  // String
  }
}
