root: true
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
    - "simple-import-sort"
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
ignorePatterns:
    # don't ever lint node_modules
    - "node_modules"
    - "protobufs"
    - "out"
env: 
    browser: true
    node: true
rules:
    indent:
        - error
        - 4
        - SwitchCase: 1
    max-len:
        - warn
        - code: 160
    no-cond-assign: warn
    no-multiple-empty-lines:
        - error
        - max: 3
    no-trailing-spaces: error
    semi: "off"
    comma-dangle: "off"
    quotes:
        - error
        - "double"
    no-console: warn
    interface-name: "off"
    one-line: "off"
    member-ordering: "off"
    object-literal-sort-keys: "off"
    eol-last:
        - error
        - "always"
    no-shadow: "off"
    object-curly-spacing:
        - warn
        - "always"
    array-bracket-spacing:
        - warn
        - "always"
    simple-import-sort/imports:
        - 2
        - groups:
            -   # Packages come first.
                - "^@?\\w"
            -   # Parent imports. Put `..` last.
                - "^\\.\\.(?!/?$)"
                - "^\\.\\./?$"
            -   # Other relative imports. Put same-folder imports and `.` last.
                - "^\\./(?=.*/)(?!/?$)"
                - "^\\.(?!/?$)"
                - "^\\./?$"

    "@typescript-eslint/explicit-member-accessibility": error
    "@typescript-eslint/explicit-function-return-type":
        - error
        - allowExpressions: true
    "@typescript-eslint/no-inferrable-types": "off"
    "@typescript-eslint/no-magic-numbers":
        - warn
        - ignoreReadonlyClassProperties: true
          ignoreEnums: true
          ignore: [ 0 ]
    "@typescript-eslint/array-type":
        - error
        - array: true
    "@typescript-eslint/semi":
        - error
    "@typescript-eslint/comma-dangle":
        - error
        -   # General rule for everything doesn't work with functions
            enums: "always-multiline"
            generics: "always-multiline"
            tuples: "always-multiline"
            arrays: "always-multiline"
            objects: "always-multiline"
            imports: "always-multiline"
            exports: "always-multiline"
            functions: "always-multiline"
    "@typescript-eslint/member-delimiter-style":
        - error
        - singleline:
            delimiter: "comma"
            requireLast: false
    "@typescript-eslint/no-shadow":
        - warn
        - ignoreTypeValueShadow: true
    "@typescript-eslint/consistent-type-imports":
        - warn
        - prefer: type-imports
