name: Create Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  release:

    name: Create Release
    runs-on: ubuntu-latest
    # NOTE: Created release will trigger artifact compilation and we need to have SDK published for that
    needs: publish-rust

    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          # NOTE: Custom token is used so release event will be emitted
          token: ${{ secrets.OPS_GITHUB_TOKEN }}

  publish-rust:
  
    runs-on: ubuntu-latest

    env:
      M10_PROTOBUFS: "${{ github.workspace }}/protobuf"

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          echo "PROTOC=$(which protoc)" >> $GITHUB_ENV
      - uses: katyo/publish-crates@v2
        with:
          path: "./rust"
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true

  publish-node:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: node/m10-sdk

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: yarn install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-dart:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@main
    with:
      working-directory: flutter/m10_sdk
