name: Create Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  release:

    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true

  add-artifacts:

    name: Compile ${{ matrix.target }}
    runs-on: ubuntu-latest

    needs: release

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip

    steps:
      - uses: actions/checkout@v3
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          SRC_DIR: examples/m10_cli
          PRE_BUILD: .github/utils/setup-protoc.sh
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

  # publish-rust:
  
  #   runs-on: ubuntu-latest
  #   env:
  #     M10_PROTOBUFS: "${{ github.workspace }}/protobuf"

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         override: true
  #     - uses: katyo/publish-crates@v2
  #       with:
  #         path: "./rust"
  #         registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  #         ignore-unpublished-changes: true

  # publish-node:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "16.x"
  #         registry-url: "https://registry.npmjs.org"
  #     - run: npm install
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # publish-dart:

  #   uses: dart-lang/setup-dart/.github/workflows/publish.yml@main
  #   with:
  #     working-directory: flutter/m10_sdk
