name: Publish to npmjs.com

defaults:
  run:
    working-directory: node/m10-sdk

on:
  push:
    tags:
      # - "v[0-9]+.[0-9]+.[0-9]+"
      - "disabled"

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
