name: Publish to crates.io

on:
  # push:
  #   tags:
  #     - "*"
  # NOTE: Enable manual trigger from Actions tab
  workflow_dispatch:

env:
  M10_PROTOBUFS: "${{ github.workspace }}/protobuf"

jobs:

  publish:
  
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: katyo/publish-crates@v2
        with:
          path: "./rust"
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
